import streamlit as st
import datetime

# 🧠 Import local travel planner logic
from travel_agent import get_travel_plan

st.set_page_config(
    page_title="🌍 Travel Made Easy",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Made Easy")

if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("How can I help you in planning a trip? Let me know where you want to visit.")

# Chat input box
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder=" Please give your desired location and duration")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    with st.spinner("Bot is thinking..."):
        answer = get_travel_plan(user_input)

    markdown_content = f"""# 🌍 AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**Created by:** Gyan's Travel Agent

---

{answer}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""
    st.markdown(markdown_content)
