import streamlit as st
import datetime

def get_travel_plan(question: str) -> str:
    try:
        from travel_agent import get_travel_plan as run_plan
        return run_plan(question)
    except Exception as exc:
        return (
            "Error: Unable to initialize the travel planner backend. "
            "Please verify dependencies and environment variables. "
            f"Details: {exc}"
        )


def transcribe_audio(uploaded_file) -> str:
    from utils.speech_to_text import transcribe_audio as run_transcription
    return run_transcription(uploaded_file)


st.set_page_config(
    page_title="🌍 Travel Made Easy",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Made Easy")

st.header("How can I help you in planning a trip?")

# -----------------------------
# TEXT INPUT
# -----------------------------
st.subheader("⌨️ Type your travel request")

with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input(
        "User Input",
        placeholder="e.g. 5-day trip to Paris with budget breakdown"
    )
    submit_button = st.form_submit_button("Send")

# -----------------------------
# VOICE INPUT
# -----------------------------
st.subheader("🎙️ Or speak your travel request")

audio_file = st.file_uploader(
    "Upload an audio file (wav / mp3 / m4a)",
    type=["wav", "mp3", "m4a"]
)

# -----------------------------
# HANDLE TEXT QUERY
# -----------------------------
if submit_button and user_input.strip():
    with st.spinner("🤖 Planning your trip..."):
        answer = get_travel_plan(user_input)

    st.markdown(
        f"""
# 🌍 AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**Created by:** Gyan's Travel Agent

---

{answer}

---

*This travel plan was generated by AI. Please verify prices, timings, and travel requirements before booking.*
"""
    )

# -----------------------------
# HANDLE VOICE QUERY
# -----------------------------
if audio_file is not None:
    try:
        with st.spinner("🎧 Transcribing audio..."):
            spoken_text = transcribe_audio(audio_file)
    except Exception as exc:
        st.error(
            "Voice transcription is currently unavailable. "
            f"Details: {exc}"
        )
        st.stop()

    st.success(f"🗣️ You said: **{spoken_text}**")

    with st.spinner("🤖 Planning your trip..."):
        answer = get_travel_plan(spoken_text)

    st.markdown(
        f"""
# 🌍 AI Travel Plan (from Voice Input)

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**Created by:** Gyan's Travel Agent

---

{answer}

---

*This travel plan was generated by AI. Please verify prices, timings, and travel requirements before booking.*
"""
    )
